# =========================================
# Stage: Development (Vite React.js App)
# =========================================
ARG NODE_VERSION=24.14.0-alpine
 
FROM node:${NODE_VERSION} AS dev
 
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Enable Corepack and activate pnpm
RUN corepack enable
# Set working directory inside the container
WORKDIR /app
 
# Copy package files
COPY package*.json ./
 
# Copy rest of the source code
COPY . .
 
# Ensure the "node" user owns the application files
RUN chown -R node:node /app
 
# Use --mount=type-cache for efficient caching of the pnpm store 
RUN npm install pnpm
RUN pnpm install

RUN mkdir /app/node_modules/.vite \
    && chown -R node:node /app/node_modules/.vite

# Switch to the built-in non-root "node" user
USER node
 
# Expose Vite dev server port
EXPOSE 5173
 
# Run Vite in dev mode, accessible outside the container
CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]
